import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build, type Random} from './build.ts';
import {identity, balance, combine, pairNode, paddingIdentity, tree, audit, verify, stringify, parse, MAX, type Bundle} from './tree.ts';
const snapshot=`0x${'01'.repeat(32)}` as const;
const customers=[{customerId:'alice-secret-id',dateOfBirth:'1990-12-30',balance:100n},{customerId:'bob-secret-id',dateOfBirth:'1999-01-20',balance:71n},{customerId:'charlie-secret-id',dateOfBirth:'1980-01-01',balance:39n}];
export function fixture() { let n=0n; const random:Random={secret:()=>`0x${(++n).toString(16).padStart(64,'0')}`,below:limit=>(++n)%limit}; return build(customers,snapshot,16,2,4,random); }
const expected={customerId:customers[0].customerId,dateOfBirth:customers[0].dateOfBirth,balance:100n};
test('deterministic identity and ABI leaf/pair/parent sums',()=>{const {bundles:[b]}=fixture();const p=b.parts[0];const id=identity(snapshot,b.customerId,b.dateOfBirth,0,p.salt,p.nonce);assert.equal(id,identity(snapshot,b.customerId,b.dateOfBirth,0,p.salt,p.nonce)); assert.notEqual(id,identity(snapshot,b.customerId,b.dateOfBirth,0,p.nonce,p.salt)); assert.equal(pairNode(snapshot,0,{identity:id,amount:10n}).sum,10n);assert.equal(combine(balance(snapshot,0,10n),balance(snapshot,1,20n)).sum,30n);});
test('every customer verifies shuffled parts and independent full balances',()=>{const {ledger,bundles}=fixture();assert.equal(ledger.rootSum,210n);assert.ok(audit(ledger));bundles.forEach((b,i)=>assert.ok(verify(b,{...customers[i],balance:customers[i].balance},ledger)));assert.ok(verify(parse<Bundle>(stringify(bundles[0])),expected,ledger));});
test('fixed public capacity, padding, one, odd, empty and maximum customers',()=>{for (const n of [0,1,3,8]) {const result=build(Array.from({length:n},(_,i)=>({...customers[0],customerId:String(i)})),snapshot,16,2,2);assert.equal(tree(snapshot,16,result.ledger.pairs).levels[0].length,16);assert.ok(audit(result.ledger));}assert.throws(()=>build(Array.from({length:9},(_,i)=>({...customers[0],customerId:String(i)})),snapshot,16,2,2));});
test('public format contains amounts and commitments but no customer openings or mapping',()=>{const {ledger,bundles}=fixture();const publicJson=stringify(ledger);for (const b of bundles){assert.ok(!publicJson.includes(b.customerId));assert.ok(!publicJson.includes(b.dateOfBirth));for(const p of b.parts){assert.ok(!publicJson.includes(p.salt));assert.ok(!publicJson.includes(p.nonce));}}assert.deepEqual(Object.keys(ledger.pairs[0]),['identity','amount']);assert.equal(new Set(ledger.pairs.map(p=>p.identity)).size,ledger.pairs.length);});
test('balance changes, swapped balance children and independently shuffled identity children change root',()=>{const {ledger}=fixture();for(const mutate of [(p:typeof ledger.pairs)=>{p[0].amount++},(p:typeof ledger.pairs)=>{[p[0].amount,p[1].amount]=[p[1].amount,p[0].amount]},(p:typeof ledger.pairs)=>{[p[0].identity,p[1].identity]=[p[1].identity,p[0].identity]}]){const changed=structuredClone(ledger);mutate(changed.pairs);assert.ok(!audit(changed));}});
const mutations:Record<string,(b:Bundle)=>void>={
 'customer ID':b=>{b.customerId='other'}, 'date of birth':b=>{b.dateOfBirth='2000-01-01'}, salt:b=>{b.parts[0].salt=snapshot},nonce:b=>{b.parts[0].nonce=snapshot},balance:b=>{b.parts[0].amount++},'sibling hash':b=>{b.parts[0].siblings[0].hash=snapshot},'sibling sum':b=>{b.parts[0].siblings[0].sum++},direction:b=>{b.parts[0].path[0]^=1},root:b=>{b.rootHash=snapshot},total:b=>{b.rootSum++},epoch:b=>{b.snapshotId=`0x${'02'.repeat(32)}`},negative:b=>{b.parts[0].amount=-1n},overflow:b=>{b.parts[0].amount=MAX+1n},'missing part':b=>{b.parts.pop()},'duplicate part index':b=>{b.parts[1].partIndex=b.parts[0].partIndex},'duplicate position':b=>{b.parts[1].pairPosition=b.parts[0].pairPosition},'reused salt':b=>{b.parts[1].salt=b.parts[0].salt},'reused nonce':b=>{b.parts[1].nonce=b.parts[0].nonce},'expected balance':b=>{b.expectedBalance++},capacity:b=>{b.capacity=8},'missing path':b=>{b.parts[0].path.pop()}
};
for(const [name,mutate] of Object.entries(mutations))test(`reject ${name}`,()=>{const {ledger,bundles:[b]}=fixture();mutate(b);assert.equal(verify(b,expected,ledger),false)});
test('independently incorrect identity, balance or anchor fails',()=>{const {ledger,bundles:[b]}=fixture();assert.ok(!verify(b,{...expected,balance:101n},ledger));assert.ok(!verify(b,{...expected,customerId:'bob'},ledger));assert.ok(!verify(b,expected,{...ledger,rootSum:211n}));});
test('reject reused randomness, negative values, overflow, invalid capacity, duplicate customers and zero parts',()=>{assert.throws(()=>build(customers,snapshot,16,2,4,{secret:()=>snapshot,below:()=>0n}));assert.throws(()=>build([{...customers[0],balance:-1n}],snapshot));assert.throws(()=>tree(snapshot,2,[{identity:snapshot,amount:MAX},{identity:`0x${'02'.repeat(32)}`,amount:1n}]));assert.throws(()=>build(customers,snapshot,3));assert.throws(()=>build([customers[0],customers[0]],snapshot));assert.throws(()=>build([{...customers[0],balance:0n}],snapshot));assert.throws(()=>tree(snapshot,2,[{identity:snapshot,amount:0n}]));assert.throws(()=>parse('{"amount":-1}'));});
